# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-16 09:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('carat', models.IntegerField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.IntegerField()),
                ('user_contact_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+96565624892'. Up to 10 digits allowed", regex='^\\+?1?\\d{8,12}$')])),
                ('order_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=100)),
                ('user_contact_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+96565624892'. Up to 10 digits allowed", regex='^\\+?1?\\d{8,12}$')])),
            ],
        ),
        migrations.CreateModel(
            name='UserAddresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(max_length=500)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='murtazabhaiapp.UserAccount')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='murtazabhaiapp.UserAddresses'),
        ),
        migrations.AddField(
            model_name='orders',
            name='item_ordered_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='murtazabhaiapp.Items'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='murtazabhaiapp.UserAccount'),
        ),
        migrations.AddField(
            model_name='itemimages',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='murtazabhaiapp.Items'),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='murtazabhaiapp.Items'),
        ),
    ]
