# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-16 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murtazabhaiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_id',
            field=models.IntegerField(unique=True),
        ),
    ]
