# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-16 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murtazabhaiapp', '0002_auto_20171216_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimages',
            name='item_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
