# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-16 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('murtazabhaiapp', '0003_auto_20171216_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemimages',
            old_name='property',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='useraddresses',
            old_name='property',
            new_name='user',
        ),
    ]
