# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-30 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murtazabhaiapp', '0004_auto_20171216_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_token',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
