# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-03 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murtazabhaiapp', '0005_auto_20171230_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='carat',
            new_name='item_carat',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='color',
            new_name='item_color',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='price',
            new_name='item_price',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='quantity',
            new_name='item_quantity',
        ),
        migrations.AddField(
            model_name='items',
            name='item_image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
