# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-15 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('murtazabhaiapp', '0006_auto_20180103_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='id',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='user',
            field=models.ForeignKey(db_column='user_email', default=1, on_delete=django.db.models.deletion.CASCADE, to='murtazabhaiapp.UserAccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='item_id',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='murtazabhaiapp.Items'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_email',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
