# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-15 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('murtazabhaiapp', '0007_auto_20180115_0721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='item_id',
            new_name='item',
        ),
    ]
