# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-27 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('murtazabhaiapp', '0008_auto_20180115_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='murtazabhaiapp.Items'),
        ),
    ]
