# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-31 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('murtazabhaiapp', '0010_auto_20180130_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.IntegerField()),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='murtazabhaiapp.UserAddresses')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='murtazabhaiapp.Items')),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='item_ordered_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity_ordered',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='user_token',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='murtazabhaiapp.UserAccount'),
        ),
        migrations.AddField(
            model_name='orders',
            name='ordered_item',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_item', to='murtazabhaiapp.OrderedItem'),
            preserve_default=False,
        ),
    ]
