# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-31 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('murtazabhaiapp', '0012_auto_20180131_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='delivery_address',
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='murtazabhaiapp.UserAddresses'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='murtazabhaiapp.Items'),
        ),
    ]
