# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-09 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murtazabhaiapp', '0014_auto_20180203_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user_contact_number',
        ),
        migrations.AddField(
            model_name='items',
            name='item_weight',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='order_date',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='order_status',
            field=models.CharField(max_length=30),
        ),
    ]
