# Generated by Django 2.0.4 on 2018-04-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murtazabhaiapp', '0017_items_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='item',
            field=models.OneToOneField(on_delete=None, related_name='item', to='murtazabhaiapp.Items'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='user',
            field=models.ForeignKey(db_column='user_email', on_delete=None, to='murtazabhaiapp.UserAccount'),
        ),
        migrations.AlterField(
            model_name='itemimages',
            name='item',
            field=models.ForeignKey(on_delete=None, related_name='images', to='murtazabhaiapp.Items'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='item',
            field=models.OneToOneField(on_delete=None, related_name='order_item', to='murtazabhaiapp.Items'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='order_id',
            field=models.ForeignKey(db_column='order_id', on_delete=None, to='murtazabhaiapp.Orders'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='user_email',
            field=models.ForeignKey(db_column='user_email', on_delete=None, to='murtazabhaiapp.UserAccount'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_address',
            field=models.ForeignKey(on_delete=None, related_name='delivery_address', to='murtazabhaiapp.UserAddresses'),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='user_email',
            field=models.ForeignKey(db_column='user_email', on_delete=None, to='murtazabhaiapp.UserAccount'),
        ),
    ]
