# Generated by Django 2.0.4 on 2018-04-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murtazabhaiapp', '0018_auto_20180407_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
