# Generated by Django 2.0.7 on 2018-07-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murtazabhaiapp', '0019_items_item_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='user',
            new_name='user_email',
        ),
        migrations.RemoveField(
            model_name='items',
            name='id',
        ),
        migrations.RemoveField(
            model_name='items',
            name='item_size',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='item_size',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitems',
            name='item_size_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='item_size',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='item_size_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='item',
            field=models.ForeignKey(on_delete=None, related_name='item', to='murtazabhaiapp.Items'),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_type',
            field=models.CharField(choices=[('ring', 'RING'), ('bracelet', 'BRACELET'), ('necklace', 'NECKLACE'), ('chain', 'CHAIN'), ('earring', 'EARRING'), ('anklet', 'ANKLET')], default='bracelet', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='item',
            field=models.ForeignKey(on_delete=None, related_name='order_item', to='murtazabhaiapp.Items'),
        ),
    ]
