# Generated by Django 2.0.7 on 2018-07-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murtazabhaiapp', '0020_auto_20180711_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddresses',
            old_name='user_building_details',
            new_name='user_block',
        ),
        migrations.RenameField(
            model_name='useraddresses',
            old_name='user_street_details',
            new_name='user_floor',
        ),
        migrations.RenameField(
            model_name='useraddresses',
            old_name='user_country',
            new_name='user_jedda',
        ),
        migrations.RemoveField(
            model_name='useraddresses',
            name='user_pincode',
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='user_description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddresses',
            name='user_house',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddresses',
            name='user_other_contact_info',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddresses',
            name='user_street',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='item',
            field=models.ForeignKey(db_column='item', on_delete=None, to='murtazabhaiapp.Items'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='item_size',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='item_size_type',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_price',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_weight',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='item',
            field=models.ForeignKey(db_column='order_item', on_delete=None, to='murtazabhaiapp.Items'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='item_size',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='item_size_type',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_address',
            field=models.ForeignKey(db_column='delivery_address', on_delete=None, to='murtazabhaiapp.UserAddresses'),
        ),
    ]
